name: wishfly
description: Wishfly allows you to know what functions should your app have. All in your app.
version: 0.0.8
repository: https://github.com/Wishfly-dev/client

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  wishfly_shared: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/l10n/
